### ISSUE TITLE
adsAsynPortDriverCyclicThread freezes when it attemps to connect for the first time on Windows

### ISSUE THREAD

**Issue by hanak** [EuropeanSpallationSource/epics-twincat-ads#4]
Even though the project is not compatible with Windows, it is possible to build it using MSVS with some patching of Makefile. Yet, the adsAsynPortDriverCyclicThread freezes on adsLock(). Upon closer inspection, it looks like the cause is the line
```
adsUnlock();
```
in `adsAsynPortDriver::adsAsynPortDriver`. It looks like `adsUnlock()` is called with no `adsLock()` preceding it. `adsUnlock()` uses `std::mutex`. According to https://en.cppreference.com/w/cpp/thread/mutex/unlock, calling `std::mutex::unlock()` while the thread does not own the mutex results into undefined behavior. It seems this has no effect on Linux. Yet, it causes a deadlock on Windows (MSVS 2019). Even though the reason behind it is not known to me, it seems to me this is covered by "undefined behavior" promised in the documentation.

Sadly, I do not have the ADS compatible device available yet. Thus, I cannot test a fix. Therefore, I have created this issue instead of a pull request so the issue can be tracked.

Is this `adsUnlock()` just a forgotten leftover (because there is no call usually protected by `adsLock()/adsUnlock()` before the line in question) or is it any else?

**Comment by tboegi** [comment]
Thanks for the report.
I am sure, that we have never test this under WIndows.
However, a PR will be appreciated, you can mark it as Draft,
if you want.

**Comment by hanak** [comment]
Sure. I have created a pull request #5.

**Comment by tboegi** [comment]
Yes, thanks.
I will comment on the PR instead

**Comment by tboegi** [comment]
Fixed in https://github.com/EuropeanSpallationSource/epics-twincat-ads/commit/045f40f2e80057025befe015b89b80288157c479
